language: c

sudo: requires

before_install:
  - mkdir -p /tmp/scratch

install:
  - ./tools/install-chibi
  - ./tools/build-native-library
  - ./tools/install-self

script:
  - ./tools/run-all-tests
